

const wine = {
    50: "#F5E0E5",
    100: "#E7B2BF",
    200: "#D78196",
    300: "#C65270",
    400: "#BA3255",
    500: "#AE143D",
    600: "#A0113B",
    700: "#8C0F37",
    800: "#780C33",
    900: "#550A2B",
  }
  const blue = {
    50: "#E2E7FF",
    100: "#B5C4FF",
    200: "#849EF2",
    300: "#527ADE",
    400: "#205DD0",
    500: "#0042C2",
    600: "#003AB8",
    700: "#0031AC",
    800: "#0027A0",
    900: "#00158A",
  }
  const purple = {
    50: "#F1E3FC",
    100: "#DCB9F8",
    200: "#C28CED",
    300: "#A562DE",
    400: "#9142D3",
    500: "#7D23C7",
    600: "#6C22C1",
    700: "#541FB8",
    800: "#3C1DB0",
    900: "#0019A1",
  }
  const cold = {
    50: "#F6F8FF",
    100: "#EEF0FB",
    200: "#E4E6F1",
    300: "#D4D6E0",
    400: "#C4C6D0",
    500: "#A6A8B1",
    600: "#7C7E87",
    700: "#54565F",
    800: "#363840",
    900: "#16181F",
  }
  const warm = {
    50: "#FDFBFB",
    100: "#F8F7F7",
    200: "#F3F2F2",
    300: "#EBEAEA",
    400: "#C9C8C8",
    500: "#ABAAAA",
    600: "#818080",
    700: "#6D6C6C",
    800: "#4D4C4C",
    900: "#2B2A2A",
  }
  const green = {
    50: "#E3F4EB",
    100: "#BCE3CD",
    200: "#91D0AD",
    300: "#62BF8D",
    400: "#39B276",
    500: "#00A55E",
    600: "#009654",
    700: "#008448",
    800: "#00733D",
    900: "#005428",
  }
  const yellow = {
    50: "#FFFBEB",
    100: "#FEF3C7",
    200: "#FDE68A",
    300: "#FCD34D",
    400: "#FBBF24",
    500: "#F59E0B",
    600: "#D97706",
    700: "#B45309",
    800: "#92400E",
    900: "#78350F",
  }
  const red = {
    50: "#FFEDEA",
    100: "#FFDAD6",
    200: "#FFB4AB",
    300: "#FF897D",
    400: "#FF5449",
    500: "#DE3730",
    600: "#BA1A1A",
    700: "#93000A",
    800: "#690005",
    900: "#410002",
  }
  
  /** @type {import('tailwindcss').Config} */
  export default {
    darkMode: "class",
    content: [
      './pages/**/*.{ts,tsx}',
      './components/**/*.{ts,tsx}',
      './app/**/*.{ts,tsx}',
      './src/**/*.{js,jsx,ts,tsx}',
    ],
    prefix: "",
    theme: {
      container: {
        center: true,
        padding: "2rem",
        screens: {
          "2xl": "1400px",
        },
      },
      extend: {
        perspective: {
          'default': '1000px',
        },
        rotate: {
          'y-180': 'rotateY(180deg)',
        },
        backfaceHidden: {
          'backface-hidden': 'backface-visibility: hidden',
        },
        boxShadow: {
          DEFAULT:
            "0 1px 3px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(0, 0, 0, 0.02)",
          md: "0 4px 6px -1px rgba(0, 0, 0, 0.08), 0 2px 4px -1px rgba(0, 0, 0, 0.02)",
          lg: "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.01)",
          xl: "0 20px 25px -5px rgba(0, 0, 0, 0.08), 0 10px 10px -5px rgba(0, 0, 0, 0.01)",
        },
        outline: {
          blue: "2px solid rgba(0, 112, 244, 0.5)",
        },
        fontFamily: {
          inter: ["Inter", "sans-serif"],
          roboto: ["Roboto"],
          lexend: ["Lexend Deca"],
        },
        fontSize: {
          xxs: ["0.625rem", { lineHeight: "1.5" }],
          xs: ["0.75rem", { lineHeight: "1.5" }],
          sm: ["0.875rem", { lineHeight: "1.5715" }],
          base: ["1rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
          lg: ["1.125rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
          xl: ["1.25rem", { lineHeight: "1.5", letterSpacing: "-0.01em" }],
          "2xl": ["1.5rem", { lineHeight: "1.33", letterSpacing: "-0.01em" }],
          "3xl": ["1.88rem", { lineHeight: "1.33", letterSpacing: "-0.01em" }],
          "4xl": ["2.25rem", { lineHeight: "1.25", letterSpacing: "-0.02em" }],
          "5xl": ["3rem", { lineHeight: "1.25", letterSpacing: "-0.02em" }],
          "6xl": ["3.75rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        },
        screens: {
          xs: "480px",
        },
        borderWidth: {
          3: "3px",
        },
        minWidth: {
          36: "9rem",
          44: "11rem",
          56: "14rem",
          60: "15rem",
          72: "18rem",
          80: "20rem",
        },
        maxWidth: {
          "8xl": "88rem",
          "9xl": "96rem",
        },
        zIndex: {
          60: "60",
        },
        colors: {
          wine,
          blue,
          purple,
          cold,
          warm,
          green,
          yellow,
          red,
          "text-primary": "rgb(var(--text-primary), <alpha-value>)",
          "text-secondary": "rgb(var(--text-secondary), <alpha-value>)",
          "text-tertiary": "rgb(var(--text-tertiary), <alpha-value>)",
          "text-brand": "rgb(var(--text-brand), <alpha-value>)",
          "text-brand-hover": "rgb(var(--text-brand-hover), <alpha-value>)",
          "text-invert": "rgb(var(--text-invert), <alpha-value>)",
          "text-disabled": "rgb(var(--text-disabled), <alpha-value>)",
          "text-info": "rgb(var(--text-info), <alpha-value>)",
          "text-info-soft": "rgb(var(--text-info-soft), <alpha-value>)",
          "text-warning": "rgb(var(--text-warning), <alpha-value>)",
          "text-warning-soft": "rgb(var(--text-warning-soft), <alpha-value>)",
          "text-positive": "rgb(var(--text-positive), <alpha-value>)",
          "text-positive-soft": "rgb(var(--text-positive-soft), <alpha-value>)",
          "text-negative": "rgb(var(--text-negative), <alpha-value>)",
          "text-negative-soft": "rgb(var(--text-negative-soft), <alpha-value>)",
          "surface-primary": "rgb(var(--surface-primary), <alpha-value>)",
          "surface-secondary": "rgb(var(--surface-secondary), <alpha-value>)",
          "surface-tertiary": "rgb(var(--surface-tertiary), <alpha-value>)",
          "surface-hover": "rgb(var(--surface-hover), <alpha-value>)",
          "surface-disabled": "rgb(var(--surface-disabled), <alpha-value>)",
          "surface-invert": "rgb(var(--surface-invert), <alpha-value>)",
          "surface-invert-hover": "rgb(var(--surface-invert-hover), <alpha-value>)",
          "surface-brand": "rgb(var(--surface-brand), <alpha-value>)",
          "surface-brand-soft": "rgb(var(--surface-brand-soft), <alpha-value>)",
          "surface-brand-hover": "rgb(var(--surface-brand-hover), <alpha-value>)",
          "surface-neutral": "rgb(var(--surface-neutral), <alpha-value>)",
          "surface-neutral-soft": "rgb(var(--surface-neutral-soft), <alpha-value>)",
          "surface-neutral-hover": "rgb(var(--surface-neutral-hover), <alpha-value>)",
          "surface-info": "rgb(var(--surface-info), <alpha-value>)",
          "surface-info-soft": "rgb(var(--surface-info-soft), <alpha-value>)",
          "surface-info-hover": "rgb(var(--surface-info-hover), <alpha-value>)",
          "surface-positive": "rgb(var(--surface-positive), <alpha-value>)",
          "surface-positive-soft": "rgb(var(--surface-positive-soft), <alpha-value>)",
          "surface-positive-hover": "rgb(var(--surface-positive-hover), <alpha-value>)",
          "surface-negative": "rgb(var(--surface-negative), <alpha-value>)",
          "surface-negative-soft": "rgb(var(--surface-negative-soft), <alpha-value>)",
          "surface-negative-hover": "rgb(var(--surface-negative-hover), <alpha-value>)",
          "surface-warning": "rgb(var(--surface-warning), <alpha-value>)",
          "surface-warning-soft": "rgb(var(--surface-warning-soft), <alpha-value>)",
          "surface-warning-hover": "rgb(var(--surface-warning-hover), <alpha-value>)",
          "border-primary": "rgb(var(--border-primary), <alpha-value>)",
          "border-secondary": "rgb(var(--border-secondary), <alpha-value>)",
          "border-tertiary": "rgb(var(--border-tertiary), <alpha-value>)",
          "border-brand": "rgb(var(--border-brand), <alpha-value>)",
          "border-neutral": "rgb(var(--border-neutral), <alpha-value>)",
          "border-hover": "rgb(var(--border-hover), <alpha-value>)",
          "border-focus": "rgb(var(--border-focus), <alpha-value>)",
          "border-positive": "rgb(var(--border-positive), <alpha-value>)",
          "border-negative": "rgb(var(--border-negative), <alpha-value>)",
          "border-warning": "rgb(var(--border-warning), <alpha-value>)",
          "icon-primary": "rgb(var(--icon-primary), <alpha-value>)",
          "icon-secondary": "rgb(var(--icon-secondary), <alpha-value>)",
          "icon-invert": "rgb(var(--icon-invert), <alpha-value>)",
          "icon-disabled": "rgb(var(--icon-disabled), <alpha-value>)",
          "icon-brand": "rgb(var(--icon-brand), <alpha-value>)",
          "icon-brand-soft": "rgb(var(--icon-brand-soft), <alpha-value>)",
          "icon-info": "rgb(var(--icon-info), <alpha-value>)",
          "icon-info-soft": "rgb(var(--icon-info-soft), <alpha-value>)",
          "icon-positive": "rgb(var(--icon-positive), <alpha-value>)",
          "icon-positive-soft": "rgb(var(--icon-positive-soft), <alpha-value>)",
          "icon-negative": "rgb(var(--icon-negative), <alpha-value>)",
          "icon-negative-soft": "rgb(var(--icon-negative-soft), <alpha-value>)",
          "icon-warning": "rgb(var(--icon-warning), <alpha-value>)",
          "icon-warning-soft": "rgb(var(--icon-warning-soft), <alpha-value>)",
          "background-primary": "rgb(var(--background-primary), <alpha-value>)",
          "background-secondary": "rgb(var(--background-secondary), <alpha-value>)",
          "background-tertiary": "rgb(var(--background-tertiary), <alpha-value>)",
          "background-brand": "rgb(var(--background-brand), <alpha-value>)",
          "background-brand-soft": "rgb(var(--background-brand-soft), <alpha-value>)",
          "background-info": "rgb(var(--background-info), <alpha-value>)",
          "background-positive": "rgb(var(--background-positive), <alpha-value>)",
          "background-negative": "rgb(var(--background-negative), <alpha-value>)",
          "background-warning": "rgb(var(--background-warning), <alpha-value>)",
                  
          //old
          "text-brand-indigo": "#7386DF",
        },
        opacity: {
          15: "0.15",
        },
      },
    },
    plugins: [],
  };